development:
  clients:
    default:
      database: guides
      hosts:
        - localhost:27017
      options:
        user: "<%= ENV['MONGODB_USER'] %>"
        password: "<%= ENV['MONGODB_PASSWORD'] %>"
        auth_mech: :scram
        auth_source: admin
        roles:
          - 'dbOwner'
test:
  clients:
    default:
      database: tourfax_test
      hosts:
 
